export const pharmVerifyContract = {
  address: "0x5a56F899875Af59322252f1a90b4a37Fa0dDe5dc",
  abi: [
    {
      inputs: [{ internalType: "address", name: "_owner", type: "address" }],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      inputs: [],
      name: "_batchCounter",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "_issueReportCounter",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "_manufacturerCounter",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "_productCounter",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
        { internalType: "uint256", name: "_productId", type: "uint256" },
        { internalType: "string", name: "_batchNumber", type: "string" },
        { internalType: "uint256", name: "_batchQuantity", type: "uint256" },
        { internalType: "string", name: "_manufactureDate", type: "string" },
        { internalType: "string", name: "_expirationDate", type: "string" },
      ],
      name: "addBatch",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
        { internalType: "string", name: "_manufacturerName", type: "string" },
        { internalType: "string", name: "_licenseNumber", type: "string" },
        { internalType: "string", name: "_businessRegNo", type: "string" },
        { internalType: "string", name: "_companyAddress", type: "string" },
        { internalType: "string", name: "_companyPhoneNo", type: "string" },
        { internalType: "string", name: "_companyEmail", type: "string" },
        { internalType: "string", name: "_companyCountry", type: "string" },
        {
          internalType: "string",
          name: "_companyCertification",
          type: "string",
        },
        {
          internalType: "string",
          name: "_companyRegulatoryBody",
          type: "string",
        },
      ],
      name: "addManufacturer",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
        { internalType: "string", name: "_productName", type: "string" },
        { internalType: "string", name: "_productNafdacNo", type: "string" },
        { internalType: "string", name: "_productForm", type: "string" },
        { internalType: "string", name: "_activeIngredients", type: "string" },
        { internalType: "string", name: "_dosageStrength", type: "string" },
        { internalType: "string", name: "_packagingType", type: "string" },
        { internalType: "string", name: "_storageConditions", type: "string" },
        { internalType: "string", name: "_productImage", type: "string" },
      ],
      name: "addProduct",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
      ],
      name: "checkManufacturer",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "packetCode", type: "string" }],
      name: "extractBatchNumber",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "pure",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_packetCode", type: "string" }],
      name: "extractProductId",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "pure",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
        { internalType: "string", name: "_batchNumber", type: "string" },
      ],
      name: "generatePacketUniqueCodes",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "getAllManufacturers",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            {
              internalType: "address",
              name: "manufacturerAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "manufacturerName",
              type: "string",
            },
            { internalType: "string", name: "licenseNumber", type: "string" },
            { internalType: "string", name: "businessRegNo", type: "string" },
            { internalType: "string", name: "companyAddress", type: "string" },
            { internalType: "string", name: "companyPhoneNo", type: "string" },
            { internalType: "string", name: "companyEmail", type: "string" },
            { internalType: "string", name: "companyCountry", type: "string" },
            {
              internalType: "string",
              name: "companyCertification",
              type: "string",
            },
            {
              internalType: "string",
              name: "companyRegulatoryBody",
              type: "string",
            },
            {
              components: [
                { internalType: "uint256", name: "id", type: "uint256" },
                { internalType: "string", name: "productName", type: "string" },
                {
                  internalType: "string",
                  name: "productNafdacNo",
                  type: "string",
                },
                { internalType: "string", name: "productForm", type: "string" },
                {
                  internalType: "string",
                  name: "activeIngredients",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "manufacturerName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "companyAddress",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "manufacturerAddress",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "dosageStrength",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "packagingType",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "storageConditions",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "productImage",
                  type: "string",
                },
                {
                  components: [
                    { internalType: "uint256", name: "id", type: "uint256" },
                    {
                      internalType: "string[]",
                      name: "packetUniqueCodes",
                      type: "string[]",
                    },
                    {
                      internalType: "string",
                      name: "batchNumber",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "batchQuantity",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "productName",
                      type: "string",
                    },
                    {
                      internalType: "uint256",
                      name: "productId",
                      type: "uint256",
                    },
                    {
                      internalType: "string",
                      name: "manufactureDate",
                      type: "string",
                    },
                    {
                      internalType: "string",
                      name: "expirationDate",
                      type: "string",
                    },
                  ],
                  internalType: "struct YourContract.Batch[]",
                  name: "batchList",
                  type: "tuple[]",
                },
                { internalType: "bool", name: "isApproved", type: "bool" },
              ],
              internalType: "struct YourContract.Product[]",
              name: "productList",
              type: "tuple[]",
            },
            { internalType: "bool", name: "isRegistered", type: "bool" },
            {
              components: [
                { internalType: "uint256", name: "id", type: "uint256" },
                {
                  internalType: "address",
                  name: "userAddress",
                  type: "address",
                },
                { internalType: "string", name: "userName", type: "string" },
                { internalType: "string", name: "location", type: "string" },
                { internalType: "string", name: "issue", type: "string" },
                { internalType: "string", name: "productName", type: "string" },
                {
                  internalType: "string",
                  name: "productBatchNumber",
                  type: "string",
                },
                { internalType: "uint256", name: "timestamp", type: "uint256" },
              ],
              internalType: "struct YourContract.IssueReport[]",
              name: "reports",
              type: "tuple[]",
            },
          ],
          internalType: "struct YourContract.Manufacturer[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
      ],
      name: "getAllProductsByManufacturer",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "string", name: "productName", type: "string" },
            { internalType: "string", name: "productNafdacNo", type: "string" },
            { internalType: "string", name: "productForm", type: "string" },
            {
              internalType: "string",
              name: "activeIngredients",
              type: "string",
            },
            {
              internalType: "string",
              name: "manufacturerName",
              type: "string",
            },
            { internalType: "string", name: "companyAddress", type: "string" },
            {
              internalType: "address",
              name: "manufacturerAddress",
              type: "address",
            },
            { internalType: "string", name: "dosageStrength", type: "string" },
            { internalType: "string", name: "packagingType", type: "string" },
            {
              internalType: "string",
              name: "storageConditions",
              type: "string",
            },
            { internalType: "string", name: "productImage", type: "string" },
            {
              components: [
                { internalType: "uint256", name: "id", type: "uint256" },
                {
                  internalType: "string[]",
                  name: "packetUniqueCodes",
                  type: "string[]",
                },
                { internalType: "string", name: "batchNumber", type: "string" },
                {
                  internalType: "uint256",
                  name: "batchQuantity",
                  type: "uint256",
                },
                { internalType: "string", name: "productName", type: "string" },
                { internalType: "uint256", name: "productId", type: "uint256" },
                {
                  internalType: "string",
                  name: "manufactureDate",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "expirationDate",
                  type: "string",
                },
              ],
              internalType: "struct YourContract.Batch[]",
              name: "batchList",
              type: "tuple[]",
            },
            { internalType: "bool", name: "isApproved", type: "bool" },
          ],
          internalType: "struct YourContract.Product[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
        { internalType: "uint256", name: "_productId", type: "uint256" },
      ],
      name: "getBatchesForProduct",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            {
              internalType: "string[]",
              name: "packetUniqueCodes",
              type: "string[]",
            },
            { internalType: "string", name: "batchNumber", type: "string" },
            { internalType: "uint256", name: "batchQuantity", type: "uint256" },
            { internalType: "string", name: "productName", type: "string" },
            { internalType: "uint256", name: "productId", type: "uint256" },
            { internalType: "string", name: "manufactureDate", type: "string" },
            { internalType: "string", name: "expirationDate", type: "string" },
          ],
          internalType: "struct YourContract.Batch[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
      ],
      name: "getManufacturerIssues",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "address", name: "userAddress", type: "address" },
            { internalType: "string", name: "userName", type: "string" },
            { internalType: "string", name: "location", type: "string" },
            { internalType: "string", name: "issue", type: "string" },
            { internalType: "string", name: "productName", type: "string" },
            {
              internalType: "string",
              name: "productBatchNumber",
              type: "string",
            },
            { internalType: "uint256", name: "timestamp", type: "uint256" },
          ],
          internalType: "struct YourContract.IssueReport[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
        { internalType: "string", name: "_batchNumber", type: "string" },
      ],
      name: "getPacketUniqueCodesForBatch",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_manufacturerAddress",
          type: "address",
        },
        { internalType: "address", name: "_userAddress", type: "address" },
        { internalType: "string", name: "_userName", type: "string" },
        { internalType: "string", name: "_location", type: "string" },
        { internalType: "string", name: "_issue", type: "string" },
        { internalType: "string", name: "_productName", type: "string" },
        { internalType: "string", name: "_productBatchNumber", type: "string" },
      ],
      name: "reportIssue",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_uniqueCode", type: "string" }],
      name: "searchPacket",
      outputs: [
        {
          components: [
            { internalType: "string", name: "productName", type: "string" },
            { internalType: "string", name: "productNafdacNo", type: "string" },
            { internalType: "string", name: "productForm", type: "string" },
            { internalType: "string", name: "dosageStrength", type: "string" },
            { internalType: "string", name: "batchNumber", type: "string" },
            { internalType: "string", name: "manufactureDate", type: "string" },
            { internalType: "string", name: "expirationDate", type: "string" },
            {
              internalType: "string",
              name: "manufacturerName",
              type: "string",
            },
            { internalType: "string", name: "companyAddress", type: "string" },
            {
              internalType: "address",
              name: "manufacturerAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "storingCondition",
              type: "string",
            },
            {
              internalType: "string",
              name: "activeIngredients",
              type: "string",
            },
            { internalType: "string", name: "productImage", type: "string" },
            { internalType: "string", name: "comment", type: "string" },
          ],
          internalType: "struct YourContract.ProductInfo",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "withdraw",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    { stateMutability: "payable", type: "receive" },
  ],
};
